### ISSUE TITLE
Access to 30 dataset benchmark 

### ISSUE THREAD

**Issue by vtsouval** [harveyhuang18/EMR_Merging#1]
Hello,

First of all, thank you for your contribution to the community. I would like to ask if you can release the code for the 30 datasets benchmark from your paper.

**Comment by harveyhuang18** [comment]
We have updated the [doc](https://github.com/harveyhuang18/EMR_Merging/tree/main/merge_vit#extension-merging-30-vits) and you can download all the datasets now. Hopefully this can resolve your problem.

**Comment by vtsouval** [comment]
Thanks you for the swift response! 

Could you also include the data loader for those datasets (with any pre-processing) in https://github.com/harveyhuang18/EMR_Merging/tree/main/merge_vit/src/datasets

**Comment by harveyhuang18** [comment]
Hello,

Good news! We have updated the code for merging 30 ViT-B/16 models [here](https://github.com/harveyhuang18/EMR_Merging/blob/main/merge_vit/src/main_emr_30_vits.py).

The pre-processing process for the datasets is also clarified in the [doc](https://github.com/harveyhuang18/EMR_Merging/tree/main/merge_vit#extension-merging-30-vits).

**Comment by vtsouval** [comment]
Thank you,

I will try it now.
