### ISSUE TITLE
About Merging 30 ViTs

### ISSUE THREAD

**Issue by Zhengsh123** [harveyhuang18/EMR_Merging#3]
I wanted to kindly ask how you handled the dataset split for those without an official train/test division, such as Kvasir-V2/Weather/Cats_Dogs/MangoLeafBD and other similar datasets. I would greatly appreciate your insights. Thank you very much!

**Comment by harveyhuang18** [comment]
Hello,

Thanks for your attention to our work!

Actually, for those datasets without official splits, we randomly select 10% of the dataset as the test set.

Hopefully this answer can address your concern.

**Comment by Zhengsh123** [comment]
> Hello,
> 
> Thanks for your attention to our work!
> 
> Actually, for those datasets without official splits, we randomly select 10% of the dataset as the test set.
> 
> Hopefully this answer can address your concern.

Thank you very much for your reply. This is truly excellent work. I look forward to meeting you at NeurIPS!

**Comment by harveyhuang18** [comment]
Thank you!

Looking forward to meeting you at NeurIPS too (if my visa goes smoothly lol).

**Comment by vtsouval** [comment]
Hello,

Would it be possible to provide access to the pre-processed 30 datasets?

**Comment by harveyhuang18** [comment]
Hello,

The pre-processing for gray-scale datasets, including MNIST, FashionMNIST, EMNIST, are trans_gray in [code](https://github.com/harveyhuang18/EMR_Merging/blob/main/merge_vit/src/main_emr_30_vits.py) while others are trans_rgb in [code](https://github.com/harveyhuang18/EMR_Merging/blob/main/merge_vit/src/main_emr_30_vits.py).

Hopefully this can resolve your problem.
