### ISSUE TITLE
Question about EMR merging on LLMs

### ISSUE THREAD

**Issue by qq31415926** [harveyhuang18/EMR_Merging#5]
Thanks for your work. I wonder whether EMR could apply on LLMs such as Llama-3?

**Comment by harveyhuang18** [comment]
Hello!

Thanks for your interest to our work. Theoretically, EMR-Mergng can be applied to LLMs. However, limited by time, we did not conduct experiments on LLMs. You can refer to [this paper](https://arxiv.org/abs/2411.16815) and its [implementation](https://github.com/Zhengsh123/FREE-Merging), which include the experimental results of EMR-Merging on LLMs (but maybe not Llama-3).

Hopefully this could solve your problem.
